project:
  type: website

website:
  title: "Teresa Kubacka's Blog"
  navbar:
    right:
#       - about.qmd
      - icon: github
        href: https://github.com/paniterka
      - icon: twitter
        href: https://twitter.com/paniterka_ch
      - text: "Home" 
        href: http://www.teresa-kubacka.com
format:
  html:
    theme: flatly
    css: styles.css
    # mainfont: Source Sans Pro
    mainfont: Assistant
    # mainfont: Archivo
    # mainfont: Spline Sans
    toc: true
    toc-location: left 

execute: 
  freeze: auto

