project:
  type: website

website:
  title: "Teresa Kubacka's Blog"
  navbar:
    right:
#       - about.qmd
      - icon: github
        href: https://github.com/paniterka
      - icon: twitter
        href: https://twitter.com/paniterka_ch
      - text: "Home" 
        href: http://www.teresa-kubacka.com
format:
  html:
    theme: 
      - flatly
      - custom_theme.scss
    css: 
      - styles.css
      - listing_customstyle.css
    mainfont: Assistant
    toc: true
    toc-location: left 

execute: 
  freeze: auto

