project:
  type: website

website:
  title: "pythonviz.blog"
  navbar:
    right:
#       - about.qmd
      - icon: github
        href: https://github.com/paniterka
      - icon: twitter
        href: https://twitter.com/paniterka_ch
      - text: "Author" 
        href: http://www.teresa-kubacka.com
  page-footer: "(c) by Teresa Kubacka, 2022" 
format:
  html:
    theme: 
      - custom_theme.scss
    css: 
      - styles.css
      - listing_customstyle.css
    # mainfont: Assistant
    toc: true
    toc-location: left 
    include-after-body: traffic.html

execute: 
  freeze: auto

