---
title: "Installing geopandas on Windows"
date: "2023-05-26"
format: html
categories:
  - pandas
  - geodata 
---

The first time I tried to make geopandas work on Windows, I spent 2 days struggling. The [official way](https://geopandas.org/en/stable/getting_started/install.html) to install it using conda never worked for me. Finally I found a way, but I was terrified of having to do it again, so I tried to keep and reuse this virtual environment as long as I can. Unfortunately, some time ago I had to nuke my whole Anaconda installation in order to upgrade the base Python and lost the environment. Luckily, I found [this excellent tutorial](https://towardsdatascience.com/geopandas-installation-the-easy-way-for-windows-31a666b3610f) by Francis Adrian Viernes that helped me set up a geopandas environment in no time! 

Here are the steps, how they worked for me:  

1. Create a new environment (I used conda for this)
1. Know your Python version (your Python version is the same as your CPython version) by running `python -V` in your environment. Alternatively you can run `conda info` and look at `user-agent`. 
1. Install the [latest MS Visual C++ binaries](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist) for the X64 architecture ([permalink to the .exe](https://aka.ms/vs/17/release/vc_redist.x64.exe))
1. Download precompiled wheels for geopandas dependencies from [Christoph Gohlke's geospatial wheels repository](https://github.com/cgohlke/geospatial-wheels/releases)^[Note: Gohlke's wheels used to be hosted on [his University of California, Irvine webpage](https://www.lfd.uci.edu/~gohlke/pythonlibs/). This page is no longer functional.]. For a 64-bit system, choose `win_amd64` suffix. Pick the wheel for your Python version, e.g. for Python 3.9 take a wheel described as `cp39`. Do NOT change the file name.  
  - [GDAL](https://www.lfd.uci.edu/~gohlke/pythonlibs/#gdal)
  - [PyProj](https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyproj)
  - [Fiona](https://www.lfd.uci.edu/~gohlke/pythonlibs/#fiona)
  - [Shapely](https://www.lfd.uci.edu/~gohlke/pythonlibs/#shapely)  
5. Install the wheel in exactly the same sequence as listed: GDAL -> PyProj -> Fiona -> Shapely with pip. Open conda shell, navigate to the folder where your wheels are and for each wheel, run: 
```
pip install relevant_file_name.whl
```  
6. In the last step, install geopandas with pip from pypi (there is no wheel available): 
```
pip install geopandas
```


This recipe worked for Windows 10 Professional, Python 3.9.12, conda 4.12.0, pip 22.3, GDAL 3.4.3, PyProj 3.3.1, Fiona 1.8.21, Shapely 1.8.2, geopandas 0.12.1. 


